### ISSUE TITLE
Provide jQA BOM for plugin development

### ISSUE THREAD

**Issue by ascheman** [jQAssistant/jqa-bom#1]
As a plugin developer I would like to use the same dependency versions as the underlying jQAssistant release, e.g., for `slf4j-api`, to avoid conflicts during build and runtime. Therefore I suggest to extract a so-called Bill-of-Materials (BOM) from the jQA dependencies as enlisted in the parent and uber-parent `pom.xml` files and provide it as a `pom` artefact for Maven `dependencyManagement` / `import`.

Tasks
---
- [x] Create repository for the BOM
- [x] Create the basic BOM, even empty, and add it as dependency to all plugins and other components
- [ ] Check our 101, if they must be updated
- [ ] Check our Getting started for developers
- [x] Include the repository in the list of repositories to be mirrored to jqara
- [ ] Include the repository in the release tooling
- [ ] Include the repository in our Kanban Boards
- [x] Add the repository to the label updater and update the labels
- [x] Add the repository to the list of repositories for milestone management
- [ ] Maven artefact must be uploaded to OSS Sonartype
- [x] Have a pipeline in our Jenkins
- [x] Reenable the Maven Invoker Tests for the Maven Plugin for jQAssistant
- [x] Write a nice and informative readme
- [x] Release notes of the BOM are part of the releasenots overview
- [ ] Documentation of the BOM is part of the jQA documentation
- [ ] Review the dependency scops with @DirkMahler

**Comment by obfischer** [comment]
I agree with you.

@DirkMahler What do you think?

**Comment by DirkMahler** [comment]
Fully agree to it.

**Comment by obfischer** [comment]
Hi @ascheman,

would you like to act as friendly user to test a potential BOM?

**Comment by ascheman** [comment]
Hey, @obfischer,

of course I'd be happy to do some alpha or beta testing.
I discussed the issue some days ago with @DirkMahler already. 
I am happy that you picked up my proposal so fast.

Let me know what I can do (or under which coordinates I'd find appropriate BOM artefacts).

**Comment by obfischer** [comment]
Good evening @ascheman,

as soon as we have a running Jenkins pipeline for the new module, you can start with testing.

**Comment by obfischer** [comment]
Hi @DirkMahler, I can't run your seed job on Jenkins. Could you please have a look at the error, written to the console of the last build? Thank you!

**Comment by obfischer** [comment]
Hi @ascheman, an early version can be found at https://oss.sonatype.org/content/repositories/snapshots/com/buschmais/jqassistant/jqa-bom/1.11.0-SNAPSHOT/.

I think it will  not be released with 1.11.0, but with 1.11.1, as I also need more time to all the tasks related to it.

**Comment by obfischer** [comment]
I have to start from scratch. Some tests are failing after moving more and more dependencies to the BOM.

**Comment by ascheman** [comment]
Thanks for your efforts, @obfischer - I can imagine it is not so easy to find a way order the dependencies and assign them to a BOM. Will try to test your next approach as soon as you have something prepared.

**Comment by obfischer** [comment]
Hi @ascheman, the BOM contains now a minimal set of dependencies and is ready for testing. But please don't use it for any critical project or rely on it for one of the next releases.

It contains now
- XO dependencies
- SLF4J
- Lombok

Are there any other dependencies you would like to see in the BOM?

**Comment by obfischer** [comment]
Ping @ascheman

**Comment by ascheman** [comment]
Works like a charm, thanks @obfischer

**Comment by obfischer** [comment]
Hi @ascheman, thank you for your feedback. I will leave this open until all work has been done.

**Comment by ascheman** [comment]
Hmm, @obfischer / @DirkMahler, with the latest jQA Snapshot builds/BOM I now run into an error (cf. https://github.com/ascheman/jqa-ansible-plugin/runs/4758443120?check_suite_focus=true#step:4:3997):

![image](https://user-images.githubusercontent.com/456000/148735136-0b395220-042f-4301-bed2-ec883c3e5a47.png)

**Comment by obfischer** [comment]
@ascheman, could be so. Them BOM is still on its own branch and hasn't been integrated in our main development branch. I have to check this today.
